server:
  port: 8000
spring:
  application:
    name: webcloud
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: cnsupercoder@163.com
    password: 19911015dai
    mailTo: lengkristy@163.com
eureka:
  instance:
    #强制使用ip地址进行注册
    prefer-ip-address: true
    #集群模式下使用
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      #配置另外一台eureka的服务器地址，如果有多个用逗号隔开，用于eureka集群
#      defaultZone: http://192.168.0.72:8000/eureka/
  #单机模式下使用
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

logging:
  path: log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    com.cyvation: debug